# Generated by Django 4.0.6 on 2022-07-10 10:16

import creditcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_name', models.CharField(max_length=20, verbose_name='Card name')),
                ('cc_number', creditcards.models.CardNumberField(max_length=25, verbose_name='Card number')),
            ],
        ),
    ]
