# Generated by Django 4.0.6 on 2022-07-09 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal', models.CharField(max_length=12, unique=True, verbose_name='Fiscal ID')),
                ('check_sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sum')),
                ('cashback_value', models.FloatField(verbose_name='Cashback value')),
                ('on_balance', models.BooleanField(default=False, verbose_name='On Balance')),
                ('time_added', models.DateTimeField(auto_now_add=True, verbose_name='Time Added')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Who scanned')),
            ],
        ),
    ]
