# Generated by Django 4.0.6 on 2022-07-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscal',
            name='fiscal',
            field=models.SlugField(max_length=12, unique=True, verbose_name='Fiscal ID'),
        ),
    ]
