# Generated by Django 4.0.6 on 2022-07-09 11:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashback', '0002_alter_fiscal_fiscal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fiscal',
            new_name='Check',
        ),
    ]
